In [1]:
import os
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
plt.rcParams['text.usetex'] = True

import yoda2numpy

In [2]:
numpy_hist = yoda2numpy.Yoda2Numpy()

In [16]:
label, hmap = numpy_hist(hist_type='sim', index=0, fname='ALEPH_1996_S3486095')

In [17]:
label

['xlow', 'xhigh', 'sumw', 'sumw2', 'sumwx', 'sumwx2', 'numEntries']

In [23]:
xlow = hmap['/ALEPH_1996_S3486095/d01-x01-y01'][:,0]

In [24]:
xhigh = hmap['/ALEPH_1996_S3486095/d01-x01-y01'][:,1]

In [25]:
x_edges = (xlow+xhigh)/2

In [26]:
x_edges

array([0.0025, 0.0075, 0.0125, 0.0175, 0.0225, 0.0275, 0.0325, 0.0375,
       0.045 , 0.055 , 0.07  , 0.09  , 0.11  , 0.14  , 0.18  , 0.225 ,
       0.275 , 0.325 , 0.375 , 0.45  , 0.55  , 0.65  , 0.75  ])

In [28]:
numEntries = hmap['/ALEPH_1996_S3486095/d01-x01-y01'][:,6]
numEntries

array([18., 56., 37., 31., 20., 36., 21., 14., 16., 23., 22., 19., 12.,
       20., 15., 15.,  6.,  1.,  1.,  3.,  3.,  2.,  0.])

$$numEntries = \frac{(sumw)^2}{sumw2}$$

In [29]:
sumw = hmap['/ALEPH_1996_S3486095/d01-x01-y01'][:,2]
sumw2 = hmap['/ALEPH_1996_S3486095/d01-x01-y01'][:,3]

sumw**2 /sumw2

/tmp/ipykernel_3469/3170809885.py:4: RuntimeWarning: invalid value encountered in divide
  sumw**2 /sumw2


array([18.00000851, 55.99999046, 37.0000034 , 31.00000056, 20.00000436,
       35.99999392, 21.00000602, 14.00000305, 15.99999738, 23.00000187,
       21.99999239, 18.99999488, 12.00000262, 20.00000436, 14.9999986 ,
       14.9999986 ,  6.00000131,  1.00000022,  1.00000022,  2.99999911,
        2.99999911,  2.00000044,         nan])